import { Member, Gender } from './types';

export const mockMembers: Member[] = [
  {
    id: '1',
    fullName: 'Nguyễn Tộc Thủy Tổ',
    tuName: 'Đắc Độ',
    hieuName: 'Tế Thế',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 1,
    isChief: true,
    childrenIds: ['2', '3', '7'],
    spouseIds: ['s1'],
    avatarUrl: 'https://picsum.photos/seed/ancestor/200',
    bio: 'Vị thủy tổ khai sáng dòng họ Nguyễn tại vùng đất này, vốn là bậc túc nho uyên bác, có công khai hoang lập ấp.'
  },
  {
    id: 's1',
    fullName: 'Trần Thị Thuần',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 1,
    isChief: false,
    childrenIds: ['2', '3', '7'],
    spouseIds: ['1'],
    avatarUrl: 'https://picsum.photos/seed/ancestor_wife/200'
  },
  {
    id: '2',
    fullName: 'Nguyễn Văn Khải',
    tuName: 'Minh Đức',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 2,
    isChief: true,
    parentId: '1',
    birthOrder: 1,
    childrenIds: ['4', '5', '8', '20'],
    spouseIds: ['s2'],
    avatarUrl: 'https://picsum.photos/seed/grandfather/200'
  },
  {
    id: 's2',
    fullName: 'Lê Thị Đào',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: 'le1',
    birthOrder: 1,
    childrenIds: ['4', '5', '8', '20'],
    spouseIds: ['2'],
    avatarUrl: 'https://picsum.photos/seed/grandmother/200'
  },
  // --- NHÁNH NGOẠI CỦA ÔNG NỘI (Họ Lê) ---
  {
    id: 'le1',
    fullName: 'Lê Văn Tự',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 1,
    isChief: false,
    childrenIds: ['s2', 'le2'],
    spouseIds: ['ls1'],
    avatarUrl: 'https://picsum.photos/seed/le_ancestor/200'
  },
  {
    id: 'ls1',
    fullName: 'Nguyễn Thị Bưởi',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 1,
    isChief: false,
    childrenIds: ['s2', 'le2'],
    spouseIds: ['le1'],
    avatarUrl: 'https://picsum.photos/seed/le_wife/200'
  },
  {
    id: 'le2',
    fullName: 'Lê Văn Huỳnh',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: 'le1',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/le_uncle/200'
  },
  {
    id: '3',
    fullName: 'Nguyễn Văn B',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: '1',
    birthOrder: 2,
    childrenIds: ['9', '10', '21'],
    spouseIds: ['s3'],
    avatarUrl: 'https://picsum.photos/seed/granduncle/200'
  },
  {
    id: 's3',
    fullName: 'Võ Thị Lệ',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: undefined,
    birthOrder: 2,
    childrenIds: ['9', '10', '21'],
    spouseIds: ['3'],
    avatarUrl: 'https://picsum.photos/seed/grandaunt/200'
  },
  {
    id: '7',
    fullName: 'Nguyễn Thị C',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: '1',
    birthOrder: 3,
    childrenIds: ['22'],
    spouseIds: ['s7'],
    avatarUrl: 'https://picsum.photos/seed/grandaunt_c/200'
  },
  {
    id: 's7',
    fullName: 'Hoàng Văn Vinh',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    childrenIds: ['22'],
    spouseIds: ['7'],
    avatarUrl: 'https://picsum.photos/seed/granduncle_vinh/200'
  },
  {
    id: '4',
    fullName: 'Nguyễn Văn Hùng',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: true,
    parentId: '2',
    birthOrder: 1,
    childrenIds: ['6', '11', '23'],
    spouseIds: ['s4'],
    avatarUrl: 'https://picsum.photos/seed/father/200'
  },
  {
    id: 's4',
    fullName: 'Phạm Thị Lan',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: 'm1', // Added parent for mother
    birthOrder: 1,
    childrenIds: ['6', '11', '23'],
    spouseIds: ['4'],
    avatarUrl: 'https://picsum.photos/seed/mother/200'
  },
  // --- NHÁNH NGOẠI CỦA TIẾN PHAN (Họ Phạm) ---
  {
    id: 'm0',
    fullName: 'Phạm Tộc Thủy Tổ',
    tuName: 'Trí Viễn',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 1,
    isChief: true,
    childrenIds: ['m1', 'ma1'],
    spouseIds: ['ms0'],
    avatarUrl: 'https://picsum.photos/seed/m_ancestor_top/200',
    bio: 'Vị tổ tiên đời thứ nhất của nhánh họ Phạm, người đã mang truyền thống hiếu học vào gia đình.'
  },
  {
    id: 'ms0',
    fullName: 'Lý Thị Huệ',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 1,
    isChief: false,
    childrenIds: ['m1', 'ma1'],
    spouseIds: ['m0'],
    avatarUrl: 'https://picsum.photos/seed/m_ancestor_wife_top/200'
  },
  {
    id: 'ma1',
    fullName: 'Phạm Thị Liên',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: 'm0',
    birthOrder: 2,
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/m_aunt_top/200'
  },
  {
    id: 'm1',
    fullName: 'Phạm Văn Nghị',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    parentId: 'm0',
    birthOrder: 1,
    childrenIds: ['s4', 'm2'],
    spouseIds: ['ms1'],
    avatarUrl: 'https://picsum.photos/seed/m_grandfather/200'
  },
  {
    id: 'ms1',
    fullName: 'Hoàng Thị Thảo',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 2,
    isChief: false,
    birthOrder: 1,
    childrenIds: ['s4', 'm2'],
    spouseIds: ['m1'],
    avatarUrl: 'https://picsum.photos/seed/m_grandmother/200'
  },
  {
    id: 'm2',
    fullName: 'Phạm Văn Tuấn',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: 'm1',
    birthOrder: 2,
    childrenIds: ['m3'],
    spouseIds: ['ms2'],
    avatarUrl: 'https://picsum.photos/seed/m_uncle/200'
  },
  {
    id: 'ms2',
    fullName: 'Trần Thị Hà',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    childrenIds: ['m3'],
    spouseIds: ['m2'],
    avatarUrl: 'https://picsum.photos/seed/m_aunt/200'
  },
  {
    id: 'm3',
    fullName: 'Phạm Gia Bảo',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: 'm2',
    birthOrder: 1,
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/m_cousin/200'
  },
  // --- KẾT THÚC NHÁNH NGOẠI ---
  {
    id: '5',
    fullName: 'Nguyễn Thị Hoa',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '2',
    birthOrder: 2,
    childrenIds: ['12', '24'],
    spouseIds: ['s5'],
    avatarUrl: 'https://picsum.photos/seed/aunt/200'
  },
  {
    id: 's5',
    fullName: 'Trần Văn Dũng',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    childrenIds: ['12', '24'],
    spouseIds: ['5'],
    avatarUrl: 'https://picsum.photos/seed/uncle/200'
  },
  {
    id: '8',
    fullName: 'Nguyễn Văn Tùng',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '2',
    birthOrder: 3,
    childrenIds: ['25'],
    spouseIds: ['s8'],
    avatarUrl: 'https://picsum.photos/seed/uncle_tung/200'
  },
  {
    id: 's8',
    fullName: 'Lý Thị Hà',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    childrenIds: ['25'],
    spouseIds: ['8'],
    avatarUrl: 'https://picsum.photos/seed/aunt_ha/200'
  },
  {
    id: '20',
    fullName: 'Nguyễn Văn Long',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '2',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/uncle_long/200'
  },
  {
    id: '6',
    fullName: 'Tiến Phan',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '4',
    birthOrder: 1,
    childrenIds: ['13', '26', '32'],
    spouseIds: ['s6'],
    avatarUrl: 'https://picsum.photos/seed/me/200',
    bio: 'Người con của dòng họ Nguyễn, đang công tác tại Sài Gòn nhưng luôn hướng về cội nguồn...'
  },
  {
    id: 's6',
    fullName: 'Nguyễn Thủy Tiên',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    birthOrder: 1,
    childrenIds: ['13', '26', '32'],
    spouseIds: ['6'],
    avatarUrl: 'https://picsum.photos/seed/wife/200'
  },
  {
    id: '32',
    fullName: 'Nguyễn Văn Minh',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '6',
    birthOrder: 3,
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/son_minh/200'
  },
  {
    id: '11',
    fullName: 'Nguyễn Văn Hải',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '4',
    birthOrder: 2,
    childrenIds: ['27'],
    spouseIds: ['s11'],
    avatarUrl: 'https://picsum.photos/seed/brother/200'
  },
  {
    id: 's11',
    fullName: 'Trần Thu Thủy',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    childrenIds: ['27'],
    spouseIds: ['11'],
    avatarUrl: 'https://picsum.photos/seed/sil/200'
  },
  {
    id: '23',
    fullName: 'Nguyễn Thị Mai',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '4',
    birthOrder: 3,
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/sister/200'
  },
  {
    id: '9',
    fullName: 'Nguyễn Văn Nam',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '3',
    childrenIds: ['28', '29'],
    spouseIds: ['s9'],
    avatarUrl: 'https://picsum.photos/seed/cousin_nam/200'
  },
  {
    id: 's9',
    fullName: 'Đặng Kim Anh',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    childrenIds: ['28', '29'],
    spouseIds: ['9'],
    avatarUrl: 'https://picsum.photos/seed/c_wife/200'
  },
  {
    id: '10',
    fullName: 'Nguyễn Thị Tuyết',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '3',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/cousin_tuyet/200'
  },
  {
    id: '21',
    fullName: 'Nguyễn Văn Thịnh',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '3',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/uncle_thinh/200'
  },
  {
    id: '22',
    fullName: 'Hoàng Minh Anh',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    parentId: '7',
    childrenIds: ['35', '36'],
    spouseIds: ['s22'],
    avatarUrl: 'https://picsum.photos/seed/cousin_hoang/200'
  },
  {
    id: 's22',
    fullName: 'Lê Thị Hồng',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 3,
    isChief: false,
    childrenIds: ['35', '36'],
    spouseIds: ['22'],
    avatarUrl: 'https://picsum.photos/seed/wife_hoang/200'
  },
  {
    id: '35',
    fullName: 'Hoàng Văn Nam',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '22',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/h_son_nam/200'
  },
  {
    id: '36',
    fullName: 'Hoàng Thị Tuyết Mai',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '22',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/h_daughter_mai/200'
  },
  {
    id: '12',
    fullName: 'Trần Thị Mỹ',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '5',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/niece_my/200'
  },
  {
    id: '24',
    fullName: 'Trần Văn Tú',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '5',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/nephew_tu/200'
  },
  {
    id: '25',
    fullName: 'Nguyễn Văn Đức',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '8',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/nephew_duc/200'
  },
  {
    id: '13',
    fullName: 'Nguyễn Văn An',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '6',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/son_an/200'
  },
  {
    id: '26',
    fullName: 'Nguyễn Thị Bình',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '6',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/daughter_binh/200'
  },
  {
    id: '27',
    fullName: 'Nguyễn Văn Cường',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '11',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/son_cuong/200'
  },
  {
    id: '28',
    fullName: 'Nguyễn Văn Dũng',
    isLunar: true,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '9',
    childrenIds: ['30', '31'], // Added children
    spouseIds: ['s28'],
    avatarUrl: 'https://picsum.photos/seed/cousin_dung/200'
  },
  {
    id: 's28',
    fullName: 'Hoàng Thị Yến',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    childrenIds: ['30', '31'],
    spouseIds: ['28'],
    avatarUrl: 'https://picsum.photos/seed/c_wife_28/200'
  },
  {
    id: '30',
    fullName: 'Nguyễn Văn Hải',
    isLunar: false,
    gender: Gender.MALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '28',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/kid_30/200'
  },
  {
    id: '31',
    fullName: 'Nguyễn Thị Hoa',
    isLunar: false,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 5,
    isChief: false,
    parentId: '28',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/kid_31/200'
  },
  {
    id: '29',
    fullName: 'Nguyễn Thị Em',
    isLunar: true,
    gender: Gender.FEMALE,
    isAdopted: false,
    generation: 4,
    isChief: false,
    parentId: '9',
    childrenIds: [],
    spouseIds: [],
    avatarUrl: 'https://picsum.photos/seed/cousin_em/200'
  }
];
